### ISSUE TITLE
undefined method `mecab_model_destory' for Natto::MeCab:Class

### ISSUE THREAD

**Issue by sbatbayar** [buruzaemon/natto#64]
When i visit pages this error raises randomly. Anyone had this issue before? any solution?

**Comment by buruzaemon** [comment]
Thanks for raising this issue. I will confirm this bug, and release a fix in the evening. 

Please allow me some time to work on this.

Brooke@iPhone

2015/12/24 10:29、Батбаяр Сүхбаатар <notifications@github.com> のメッセージ:

**Comment by buruzaemon** [comment]
Fixed with the following pull request: https://github.com/buruzaemon/natto/pull/65

**Comment by buruzaemon** [comment]
v1.1.0 bug fix release: https://github.com/buruzaemon/natto/releases/tag/untagged-28f4c095a1fc16019caf

@sbatbayar could you please get the latest version of the gem and confirm?
https://rubygems.org/gems/natto/versions/1.1.0

**Comment by sbatbayar** [comment]
thanks for fast response and fix. I will check it today and responde fast as possible.

**Comment by sbatbayar** [comment]
Ok still no error until now, thanks. Closing this issue.
