### ISSUE TITLE
Convert text including kanji and katakana to katakana only

### ISSUE THREAD

**Issue by nguyenkiidu** [buruzaemon/natto#77]
I'm getting an issue of converting 株式会社イースマイル  to カブシキガイシャイースマイル
is it possible?
Thanks!

**Comment by buruzaemon** [comment]
Hello, @nguyenkiidu... This is not an issue for natto, this is a question about MeCab output. As such, I am closing this issue.

However, I suggest you look at the [MeCab page on 出力フォーマット](https://taku910.github.io/mecab/format.html), as well as the n[atto Wiki page Appendix F: Output Formatting](https://github.com/buruzaemon/natto/wiki/Output-Formatting). You just need to use the %f option and take the 8th feature of the Chasen CSV output.

Hope that helps!
